<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWindowsForms>True</UseWindowsForms>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <OutputType>WinExe</OutputType>

        <AssemblyName>TRRSaveMaster</AssemblyName>
        <AssemblyTitle>TRR-SaveMaster</AssemblyTitle>
        <AssemblyProduct>TRR-SaveMaster</AssemblyProduct>
        <Version>2.41.0</Version>
        <FileVersion>$(Version)</FileVersion>
        <AssemblyVersion>$(Version)</AssemblyVersion>

        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>

        <AnalysisMode>recommended</AnalysisMode>
        <AnalysisModePerformance>all</AnalysisModePerformance>
    </PropertyGroup>

    <ItemGroup>
        <None Include="**\*.resx" SubType="Designer" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Properties\Settings.Designer.cs">
        <DesignTimeSharedInput>True</DesignTimeSharedInput>
        <AutoGen>True</AutoGen>
        <DependentUpon>Settings.settings</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <None Update="Properties\Settings.settings">
        <Generator>SettingsSingleFileGenerator</Generator>
        <LastGenOutput>Settings.Designer.cs</LastGenOutput>
      </None>
    </ItemGroup>
</Project>